// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// If env vars are missing (e.g., on GitHub Pages without secrets), avoid crashing the app.
const hasEnv = Boolean(SUPABASE_URL) && Boolean(SUPABASE_PUBLISHABLE_KEY);

export const supabase: any = hasEnv
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : (() => {
      console.warn(
        '[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is missing. Supabase features are disabled.'
      );
      const error = () => {
        throw new Error('Supabase ympäristömuuttujat puuttuvat. Lisää ne GitHub-sekreteihin.');
      };
      return {
        from: error,
        rpc: error,
        auth: {
          signInWithPassword: error,
          signOut: error,
        },
        storage: {
          from: error,
        },
      };
    })();