name: Release (Production)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: sbp_90bb3a6c779a79684f665586124f92f2201ff009
      SUPABASE_DB_PASSWORD: 9V2PdrzYSwi1nbPX
      SUPABASE_PROJECT_ID: zepwnzkqrrjjewdxymkb

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push

  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: sbp_90bb3a6c779a79684f665586124f92f2201ff009
      TF_VAR_linked_project: ${{ secrets.PRODUCTION_PROJECT_ID }}
    defaults:
      run:
        working-directory: supabase/remotes

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - run: terraform init
      - run: terraform apply -auto-approve -no-color
