name: Supabase Migrations & Functions

on:
  push:
    branches: ["*"]
    paths:
      - "supabase/migrations/**"
      - "supabase/functions/**"
      - "supabase/config.toml"
  workflow_dispatch:

jobs:
  supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push database migrations
        run: |
          supabase db push -p ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Set Edge Function secrets (if provided)
        if: ${{ secrets.AI_API_URL && secrets.AI_API_KEY && secrets.AI_MODEL }}
        run: |
          supabase secrets set \
            AI_API_URL="${{ secrets.AI_API_URL }}" \
            AI_API_KEY="${{ secrets.AI_API_KEY }}" \
            AI_MODEL="${{ secrets.AI_MODEL }}" \
            -p ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy ai-assistant function
        run: |
          supabase functions deploy ai-assistant -p ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}